apiVersion: v1
kind: Service
metadata:
  name: devops-microservice-service
  namespace: microservice
  labels:
    app: devops-microservice
spec:
  type: LoadBalancer
  selector:
    app: devops-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000